Repository CloudCannon/reseed, pull requests merged in 2020-10, with the labels that each got.

#10 Linting
  .eslintrc.json
  cli.js
  index.js
  lib/processors/css.js
  lib/processors/html.js
  lib/runner.js
  package-lock.json
  package.json
  test/cli.js
  test/css.js
  test/html.js
  test/runner.js
Labels: Linting/Cleanup, hacktoberfest-accepted

#12 Added documentation for flags
  README.md
Labels: documentation, hacktoberfest-accepted

#14 Fixes #13: Updated runner.js to get files with a glob
  lib/runner.js
  package.json
Labels: enhancement, hacktoberfest-accepted
